collider/collider/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("study.urls")),
    path('procedures/', include('procedure.urls'))
]

collider/study/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', study_select, name="index"),
    path('login/', login_page, name='staff_login'),
    path('logout/', logout_page, name="logout"),
    path('study/create/', study_create, name="create_study"),
    path('study/create/save/', study_create_save, name="create_study_save"),
    path('study/select/<int:study_id>/', study_set, name="set_study"),
    path('study/edit/<int:study_id>/', study_edit, name="edit_study"),
    path('study/edit/<int:study_id>/save/', study_edit_save, name="edit_study_save"),
    path('study/delete/<int:study_id>/', study_delete, name="study_delete")
]

collider/study/models.py
from django.db import models
from django.core.serializers.json import DjangoJSONEncoder


class Study(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    external_id = models.CharField(max_length=100)
    visits = models.JSONField(encoder=DjangoJSONEncoder, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class StudyForms(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    form_type = models.CharField(max_length=100, default="provider")
    procedures = models.JSONField(encoder=DjangoJSONEncoder, blank=True, null=True)
    zoho_billable_procs = models.JSONField(encoder=DjangoJSONEncoder, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Payouts(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    reference_code = models.SlugField(max_length=15)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class StudyJotForm(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    jotform_id = models.CharField(max_length=30, blank=True, null=True)
    jotform_name = models.CharField(max_length=300, blank=True, null=True)
    name = models.CharField(max_length=100)
    tags = models.CharField(max_length=200, blank=True, null=True)
    settings = models.JSONField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

collider/study/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.cache import cache
from .models import Study
# Create your views here.


def login_page(request):
    if request.user.is_authenticated:
        return redirect('/')
    message = ''
    if request.method == 'POST':
        user = authenticate(request=request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            message = 'Authentication failed'
    return render(request, 'login.html', {'message': message})


def logout_page(request):
    logout(request)
    return redirect('/login/')


@login_required
def study_select(request):
    """
    Lists studies so that you can set the study your currently working on
    :param request:
    :return:
    """
    user = request.user.id
    study_id = cache.get(f"current_study-{user}")
    if study_id:
        current_study = Study.objects.get(id=study_id, active=True)
    else:
        current_study = ""
    studies = Study.objects.all()
    return render(request, "study_main.html", context={"studies": studies, "current_study": current_study})


@login_required
def study_set(request, study_id):
    user = request.user.id
    cache.set(f"current_study-{user}", study_id)
    return redirect("/")


@login_required
def study_create(request):
    return render(request, "study_create.html")


@login_required
def study_create_save(request):
    rec = Study.objects.create(name=request.POST['name'],
                               slug=request.POST['name'].lower().replace(' ', '_').replace(',', '').replace("'", ""),
                               external_id=request.POST['external_id'])
    cache.set("current_study", rec.id)
    return redirect("/")


@login_required
def study_edit(request, study_id):
    study = Study.objects.get(id=study_id)
    return render(request, "study_edit.html", context={"current_study": study})


@login_required
def study_edit_save(request, study_id):
    study = Study.objects.get(id=study_id)
    study.name = request.POST['name']
    study.external_id = request.POST["external_id"]
    study.save()
    return redirect("/")


@login_required
def study_delete(request, study_id):
    current = cache.get(f"current_study{request.user.id}")
    if current == study_id:
        cache.delete(f"current_study{request.user.id}")
    study = Study.objects.get(id=study_id)
    study.active = False
    return redirect("/")

collider/study/templates/base.html
{% load static %}
<!DOCTYPE html>


<html lang="en">

	<!-- begin::Head -->
	<head>
		<base href="">
		<meta charset="utf-8" />
		<title>Collider Study Builder</title>
		<meta name="description" content="Updates and statistics">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--begin::Fonts -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <title>Collider Study Builder</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"
            integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
          integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css"
          integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">


    <link href="{% static 'css/local_styles.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'images/quantum_icon128x128.ico' %}" />

	</head>

	<body style="background-color: #f2f3f8">
    {% include "includes/header.html" %}

    {% block content %}{% endblock %}

    </div>
    {% include "includes/footer.html" %}
	</body>
</html>

collider/study/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collider Study Builder</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"
            integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
            crossorigin="anonymous" referrerpolicy="no-referrer">
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
          integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css"
          integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="{% static 'css/login.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'images/quantum_icon128x128.ico' %}" />

</head>
    <body>
    <div class="wrapper fadeInDown">
      <div id="formContent">

        <div class="fadeIn first">
          <img src="{% static 'images/quantum_logo_wht-canv350x140.png' %}" id="icon" alt="Customer Icon" style="height:45px; width:120px;padding: 5px" />
        </div>

        <form method="POST" action="/login/">
            {% csrf_token %}
          <input type="text" id="username" class="fadeIn second" name="username" placeholder="Username" required>
          <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password" required>
          <input type="submit" class="fadeIn fourth" value="Log In">

        </form>
        {% if message %}
          <h4>{{ message }}</h4>
        {% endif %}

      </div>
    </div>
</body>
</html>

collider/study/templates/standard_container.html
{% extends "base.html" %}
{% block content %}
    <div style="padding: 60px 25px 0 25px;">
        <div class="container-fluid border border-2 rounded bg-light">
            <div class="nav">
                <ol class="breadcrumb" style="margin: 0.5rem 0 0.5rem 0">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    {% block breadcrumb %}
                    {% endblock %}
                </ol>
            </div>
        </div>
         <div class="container-fluid border border-2 rounded bg-light overflow-auto"
              style="margin-top: 0.5rem; padding: 0; margin-bottom: 60px;">
             <div class="navbar border-bottom border-2 ps-2 pe-2 d-flex justify-content-between">
                 <div class="navbar-brand"><h4 class="fw-normal" style="margin-bottom: 0;">{% block content_title %}title{% endblock %}</h4></div>
                 <ul class="nav nav-pills-new">
                     {% block content_actions %}
                     {% endblock %}
                 </ul>
             </div>
             <div style="padding: 7px;">
                 {% block main_content %}Main{% endblock %}
             </div>

         </div>
{% endblock %}

collider/study/templates/study_create.html
{% extends 'standard_container.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="/">Study Management</a></li>
    <li class="breadcrumb-item active">Create Study</li>
{% endblock %}
{% block content_title %}Create Study{% endblock %}
{% block main_content %}
    <form action="/study/create/save/" method="post">
        {% csrf_token %}
        <div class="input-group mb-2">
                <div class="input-group-text">Study Name</div>
            <input type="text" name="name" required="required" class="form-control">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text">External Id</div>
            </div>
            <input type="text" name="external_id" required="required" class="form-control">
        </div>
            {% include "includes/buttons/submit_button_nocancel.html" %}
    </form>


{% endblock %}

collider/study/templates/study_edit.html
{% extends "standard_container.html" %}
{% load static %}
{% block content_title %}Edit Study ({{ current_study.name }}){% endblock %}
{% block main_content %}
    <form action="/study/edit/{{ current_study.id }}/save/" method="post">
        {% csrf_token %}
        <div class="input-group mb-2">
            <div class="input-group-text">Study Name</div>
            <input type="text" name="name" required="required"
                   class="form-control" value="{{ current_study.name }}">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-text">External Id</div>
            <input type="text" class="form-control" name="external_id"
                   required="required" value="{{ current_study.external_id }}">
        </div>
        <div class="float-right" style="padding: 10px">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
    </form>
{% endblock %}

collider/study/templates/study_main.html
{% extends 'standard_container.html' %}
{% block content_title %}Study Management{% endblock %}
{% block content_actions %}
<li class="nav-item"><a class="nav-link" href="/study/create/">Create Study</a></li>
{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Study Management{% if current_study %}({{ current_study.name }}){% endif %}</li>
{% endblock %}
{% block main_content %}
    <table class="table table-secondary table-striped">
    <thead>
    <tr>
        <th>Study</th>
        <th>External Ref</th>
        <th>Visit Count</th>
        <th>Form Count</th>
        <th>Payout Count</th>
        <th>Other Doc Count</th>
        <th>Select</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for study in studies %}
    <tr>
        <td>{{ study.name }}</td>
        <td>{{ study.external_id }}</td>
        <td>{{ study.visits|length }}</td>
        <td>{{ study.studyforms_set.all|length }}</td>
        <td>{{ study.payouts_set.all|length }}</td>
        <td>{{ study.studyjotform_set.all|length }}</td>
        <td><a href="/study/select/{{ study.id }}/"><i class="bi bi-bookmark-check-fill"></i></a></td>
        <td><a href="/study/edit/{{ study.id }}/"><i class="bi bi-pencil-square"></i></a></td>
        <td><a href="#" data-bs-toggle="modal" data-bs-target="#delete_study{{ study.id }}"><i class="bi bi-trash"></i></a></td>
    </tr>
        {% include "includes/study_delete_modal.html" %}
    {% endfor %}
    </tbody>
    </table>
{% endblock %}